#!/bin/bash
# Save and reload the history after each command finishes
export HISTSIZE=10000
export HISTFILESIZE=10000
export HISTCONTROL=ignoreboth:erasedups  # no duplicate entries
shopt -s histappend                      # append to history, don't overwrite it
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# bash prompt
PS1='\[\033[00;91m\]\u\[\033[01;34m\] \w\[\033[00m\]$(__git_ps1) \$ '


# Language PATH

# Java
export PATH="$PATH:/usr/local/jdk/bin"

# Go
export PATH="$PATH:/usr/local/go/bin"
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"

# Ruby
export PATH="$PATH:$HOME/.rbenv/bin"
eval "$(~/.rbenv/bin/rbenv init -)"

# Python
# Since we are using home compiled package, there might not be usable pyenv python
if ls ~/.pyenv/versions/* >/dev/null 2>&1; then
  export PATH="$PATH:$HOME/.pyenv/bin"
  eval "$(~/.pyenv/bin/pyenv init -)"
fi

# Nodejs
export PATH="$PATH:/usr/local/node/bin"
