#!/bin/bash
# Save and reload the history after each command finishes
export HISTSIZE=10000
export HISTFILESIZE=10000
export HISTCONTROL=ignoreboth:erasedups  # no duplicate entries
shopt -s histappend                      # append to history, don't overwrite it
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

# bash prompt
PS1='\[\033[00;91m\]\u\[\033[01;34m\] \w\[\033[00m\]$(__git_ps1) \$ '
