#!/bin/bash
set -euo pipefail

## Language installations
pkg_dir="/vagrant/packages"

# Java
sudo mkdir /usr/local/jdk
sudo tar xzf "${pkg_dir}"/jdk-*.tar.gz --strip-components=1 -C /usr/local/jdk

# Go
sudo mkdir /usr/local/go
sudo tar xzf "${pkg_dir}"/go*.linux-amd64.tar.gz --strip-components=1 -C /usr/local/go

# Ruby
git clone --depth=1 https://github.com/rbenv/rbenv.git ~/.rbenv
~/.rbenv/bin/rbenv init - >/dev/null
# Self packaged non-standard ruby 2.6.3 on CentOS7
tar xjf "${pkg_dir}"/ruby-2.6.3.tar.bz2 -C ~/.rbenv/versions/ --transform s/^ruby-//
~/.rbenv/bin/rbenv global $(ls ~/.rbenv/versions)

~/.rbenv/versions/2.6.3/bin/gem install --no-document fpm

# Python
git clone --depth=1 https://github.com/pyenv/pyenv.git ~/.pyenv
~/.pyenv/bin/pyenv init - >/dev/null
if ls "${pkg_dir}"/python-*.tar.bz2 &>/dev/null; then
    for py_pkg in $(ls "${pkg_dir}"/python-*.tar.bz2); do
        tar xjf "$py_pkg" -C ~/.pyenv/versions
    done
    ~/.pyenv/bin/pyenv global $(ls ~/.pyenv/versions)
    echo "Python is installed to Pyenv:"
    echo $(ls ~/.pyenv/versions)
fi

# Clojure
sudo curl -s https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -o /usr/local/bin/lein
sudo chmod a+x /usr/local/bin/lein
