#!/bin/bash
set -euo pipefail

echo "Lets rock"

user=vagrant
home="/home/$user"
provision_dir="/vagrant/provision"

# copy files to home
for rc in inputrc morerc; do
    cp "${provision_dir}/${rc}" "${home}/.${rc}"
    chown $user: "${home}/.${rc}"
done

# A persistent bash_history
ln -s /vagrant/bash_history "${home}/.bash_history"

# source morerc on login
echo "[[ -f ~/.morerc ]] && source ~/.morerc" >> "${home}/.bash_profile"

# yum installation
echo "lets update yum and get some packages"
(
    rpm -Uvh https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-12.noarch.rpm
    yum install -y \
        ack curl git libyaml p7zip rpm-build tig tree unzip vim zlib-devel
) &>/dev/null

# iTerm2 integration
echo "Setting up iTerm2 integration"
curl -s -L https://iterm2.com/misc/install_shell_integration.sh | sudo -u $user env -i HOME="${home}" USER="${user}" PATH="${PATH}" bash >/dev/null

# Packages installation
sudo -u $user env -i HOME="${home}" USER="${user}" PATH="${PATH}" bash "${provision_dir}/setup-packages"

# Lolcat banner
# sudo -u $user env -i HOME="${home}" USER="${user}" bash "${provision_dir}/setup-lolcat"

echo "All Good 👌"
